### ISSUE TITLE
Customisation help wanted

### ISSUE THREAD

**Issue by PitcherTear22** [rafaelmardojai/firefox-gnome-theme#136]
I have edited `dark.css` and enabled system icons and like it so far :
![Screenshot from 2020-05-09 10-40-29](https://user-images.githubusercontent.com/36493671/81464702-99aad400-91e1-11ea-9179-0fb9a2f87aec.png)
~~1) How do I change colours and disable borders **only** for headerbar CSD buttons?~~
2) How do I use the maximise/minimise/close buttons from my system GTK theme (and possibly use all assets from the theme)?
3) How do I use a separate file for my edited dark.css (name it `dracula.css` or something and add it to gitignore?) for easy updates w/o conflicts?

**Comment by rafaelmardojai** [comment]
>  2) How do I use the maximise/minimise/close buttons from my system GTK theme?

It should work out of the box, i will investigate and provide a fix.

> 3) How do I use a separate file for my edited dark.css (name it dracula.css or something and add it to gitignore?) for easy updates w/o conflicts?

Create `customChrome.css` file as described [here](https://github.com/rafaelmardojai/firefox-gnome-theme#enabling-optional-features).

**Comment by PitcherTear22** [comment]
> Create customChrome.css file as described here.

Ok I'm obviously doing it wrong.
I named it `dracula.css` and added `@import "theme/colors/dracula.css";` to `customChrome.css`,
it doesn't work (uses Adwaita colours). Also this: 
![Screenshot from 2020-05-09 11-01-24](https://user-images.githubusercontent.com/36493671/81465082-f5c32780-91e4-11ea-9935-9d847c7508ed.png)

**Comment by PitcherTear22** [comment]
Now I need help with this too, please

**Comment by rafaelmardojai** [comment]
>  2) How do I use the maximise/minimise/close buttons from my system GTK theme?
> > It should work out of the box, i will investigate and provide a fix.

It's working fine, looks like the issue is you want to archive the windows buttons of you theme.
Try removing the window buttons styling from `csd.css` and play around:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/2d10822608917a4d629b995b9247c6527901acfd/theme/parts/csd.css#L117

----

>  1) How do I change colours and disable borders only for headerbar CSD buttons?

The correct selector for those buttons is `#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton)`, append `:not(#hack)` to it so you override my theme styles.

I suppose you will need something similar to what i have done for flat buttons: 

```css
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(#hack) {
	background: transparent !important;
	box-shadow: none !important;
	border-color: transparent !important;
	border-radius: 5px !important;
}
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(#hack):hover {
	box-shadow: var(--gnome-button-box-shadow) !important;
	border-color: var(--gnome-button-border-color) !important;
	border-bottom-color: var(--gnome-button-border-accent-color) !important;
}
```

**Comment by PitcherTear22** [comment]
> It's working fine, looks like the issue is you want to archive the windows buttons of your theme. Try removing the window buttons styling from csd.css and play around:

I commented out that section (ie 118-EOF). It looks like this:
![Screenshot from 2020-05-11 12-17-53](https://user-images.githubusercontent.com/36493671/81532106-820a5180-9381-11ea-874b-ae3ef5874e6c.png)
Issues - 
1) Too close to the top (Whould I refer my gtk theme for padding values? Where do I find them? What do I change?)
2) It has adwaita's cross/square/minus icons along with the ones from the gtk theme:
![Screenshot from 2020-05-11 12-22-02](https://user-images.githubusercontent.com/36493671/81532528-2be9de00-9382-11ea-97b5-35d01ed8f09a.png)

**Comment by rafaelmardojai** [comment]
> Too close to the top (Whould I refer my gtk theme for padding values? Where do I find them? What do I change?)

You should play with the `:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container` paddings:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/2d10822608917a4d629b995b9247c6527901acfd/theme/parts/csd.css#L102-L112

Also don't forget to modify the padding that defines how much space window buttons take based on how many buttons are enabled:
https://github.com/rafaelmardojai/firefox-gnome-theme/blob/2d10822608917a4d629b995b9247c6527901acfd/theme/parts/csd.css#L14-L33

----

> It has adwaita's cross/square/minus icons along with the ones from the gtk theme:

The icons part are in `parts/icons.css` and `system-icons.css`. Override them with this:
```css
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .toolbarbutton-icon:not(#hack) {
	list-style-image: none !important;
}
```

**Comment by rafaelmardojai** [comment]
> Also don't forget to modify the padding that defines how much space window buttons take based on how many buttons are enabled:

Watching you screenshot, something like this could work: (or at least as an start point)
```css
:root[tabsintitlebar]:not([inFullscreen]) #nav-bar:not(#hack) { 
 	padding-right: 72px !important; 
 } 
:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container:not(#hack) { 
 	padding: 15px 3px !important; 
 } 
```

**Comment by PitcherTear22** [comment]
> I suppose you will need something similar to what I have done for flat buttons:
This highlights even the disabled icons when hovered over:
![image](https://user-images.githubusercontent.com/36493671/81624051-d14c9280-9412-11ea-8b5a-c0b7b50ed397.png).
Also, how do I change the space **between** the close/maximise/minimise buttons?

**Comment by rafaelmardojai** [comment]
> This highlights even the disabled icons when hovered over:

Try adding `:not([disabled])` to the selector.

```css
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(#hack):not([disabled]):hover {
	/* hover code */
}
```

>  Also, how do I change the space between the close/maximise/minimise buttons?

Modify `:root[tabsintitlebar] #titlebar .titlebar-button` margins:
```css
:root[tabsintitlebar] #titlebar .titlebar-button:not(#hack) {
	margin: 0 !important;
}
```

**Comment by PitcherTear22** [comment]
One last thing: How do I do this via `customChrome.css`?
![Screenshot_2020-05-12 Customisation help wanted · Issue #136 · rafaelmardojai firefox-gnome-theme](https://user-images.githubusercontent.com/36493671/81634757-36ad7d00-942d-11ea-88c6-87b6487663eb.png)
I tried changing values of everything here to `auto !important` in `customChrome.css` but it makes the buttons dissapear.

**Comment by rafaelmardojai** [comment]
`-moz-appearance: toolbarbutton;` ?

**Comment by rafaelmardojai** [comment]
This one was a little tricky, but i got something. Try with:
```css
:root[tabsintitlebar] #titlebar .titlebar-button:hover:not(#hack) {
	box-shadow: none !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-close:not(#hack) {
	-moz-appearance: -moz-window-button-close !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
	-moz-appearance: -moz-window-button-restore !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-min:not(#hack) {
	-moz-appearance: -moz-window-button-minimize !important;
}
```

**Comment by PitcherTear22** [comment]
`@import "theme/normal-width-tabs.css";
@import "theme/system-icons.css";
@import "theme/colors/dracula.css";


/*Make CSD buttons flat*/
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(#hack) {
	background: transparent !important;
	box-shadow: none !important;
	border-color: transparent !important;
	border-radius: 5px !important;
}
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(#hack):not([disabled]):hover {
	box-shadow: var(--gnome-button-box-shadow) !important;
	border-color: rgba(0, 0, 0, 0) !important;
	border-bottom-color: rgba(0, 0, 0, 0) !important;
	background: #565B6B !important;
}



/*Don't use Adwaita's buttons*/
:root[tabsintitlebar] #titlebar .titlebar-buttonbox .toolbarbutton-icon:not(#hack) {
	list-style-image: none !important;
}

/*Margin b/w close/max/min buttons*/
:root[tabsintitlebar] #titlebar .titlebar-button:not(#hack) {
	margin: 1px !important;
}

/*Fix padding*/
 /* Window buttons box */
 :root[tabsintitlebar] #titlebar .titlebar-buttonbox-container,
 :root[tabsintitlebar] #titlebar-buttonbox-container,
 :root[tabsintitlebar][inFullscreen] #window-controls {
 	-moz-appearance: none !important;
 	padding: 15px 9px;
 	position: absolute !important;
 	right: 0;
 	top: 0;
 	display: block !important;
 }



 /* Window buttons: at least 1 button */
 @media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button), (-moz-gtk-csd-close-button) {
 	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar:not(#hack) {
 	 padding-right: 30px !important;
  }
 }
 /* Window buttons: at least 2 buttons */
 @media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button),
        (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-close-button),
        (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
 	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar:not(#hack) {
 		padding-right: 50px !important;
 	}
 }
 /* Window buttons: 3 buttons */
 @media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
 	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar:not(#hack) {
 	 padding-right: 80px !important;
  }
 }
`
With this `customChrome.css` and lines 118-EOF commented out in `csd.css`, it is fine : 
![xyz2](https://user-images.githubusercontent.com/36493671/81687421-a7c55280-9476-11ea-9bfc-c89263877859.png)




With
> This one was a little tricky, but i got something. Try with:

added to `customChrome.css` and `csd.css` uncommented, it looks like this:
![xyz1](https://user-images.githubusercontent.com/36493671/81687914-ece98480-9476-11ea-93a1-f0adc8f797cb.png)

**Comment by rafaelmardojai** [comment]
```css
:root[tabsintitlebar] #titlebar .titlebar-button:not(#hack) {
	height: auto !important;
	width: auto !important;
	padding: 0  !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button:hover:not(#hack) {
	box-shadow: none !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-close:not(#hack) {
	-moz-appearance: -moz-window-button-close !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
	-moz-appearance: -moz-window-button-restore !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-min:not(#hack) {
	-moz-appearance: -moz-window-button-minimize !important;
}
```

**Comment by PitcherTear22** [comment]
White border around popup:
![Screenshot from 2020-05-13 10-42-55](https://user-images.githubusercontent.com/36493671/81773763-afccd300-9506-11ea-8b1a-6253d3180de6.png)

**Comment by rafaelmardojai** [comment]
> White border around popup

Related to your previous issue (#135). I will try to fix them soon.

**Comment by rafaelmardojai** [comment]
@PitcherTear22 if you don't have any other customization question, feel free to close this issue.

**Comment by PitcherTear22** [comment]
After this firefox update, some buttons have become grey and not others:
![fir](https://user-images.githubusercontent.com/36493671/82832243-32c33580-9ed8-11ea-9300-d808dbfe72e3.png)
Help please

**Comment by rafaelmardojai** [comment]
@PitcherTear22 FF version?

**Comment by PitcherTear22** [comment]
76.0.1 archlinux

**Comment by rafaelmardojai** [comment]
I can't reproduce it. I'm running 76.0.1 fedora & flatpak.

**Comment by PitcherTear22** [comment]
On 77.0 it became worse : https://imgur.com/HWR1OrB
The maximise button dissapears when maximised

**Comment by PitcherTear22** [comment]
`customchrome.css` : https://hastebin.com/owarurotuy.css
`theme/colors/dracula.css`: https://hastebin.com/jucavoboho.m

**Comment by rafaelmardojai** [comment]
I have added some fixes for FF77.
Update and let me know what issues persists for you.

**Comment by PitcherTear22** [comment]
urlbar is fixed, the other two issues remain

**Comment by rafaelmardojai** [comment]
What dracula GTK theme are you using? Don't seems to be Ant-Dracula.

**Comment by PitcherTear22** [comment]
Flat-remix-dark

**Comment by PitcherTear22** [comment]
> After this firefox update, some buttons(back, home and 3 dot/hamburger menu) have become grey and not others:
> ![fir](https://user-images.githubusercontent.com/36493671/82832243-32c33580-9ed8-11ea-9300-d808dbfe72e3.png)
> Help please

Disabling `system-icons.css` fixes this

**Comment by rafaelmardojai** [comment]
The icons color issue might be related to the `--gnome-icons-hack-filter` var you have overwritten.

**Comment by PitcherTear22** [comment]
> The icons color issue might be related to the `--gnome-icons-hack-filter` var you have overwritten.

Yep fixed

**Comment by rafaelmardojai** [comment]
About the maximise button issue, can you reproduce it with vanilla Firefox?

**Comment by PitcherTear22** [comment]
> About the maximise button issue. Could you try to reproduce it with vanilla Firefox?

w/o css or w/o gtk?

**Comment by rafaelmardojai** [comment]
with out userchrome css

**Comment by PitcherTear22** [comment]
It is fine without userchrome css

**Comment by rafaelmardojai** [comment]
I found the solution. In your `customChrome.css` you should replace:
```css
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
	-moz-appearance: -moz-window-button-restore !important;
}
```

With:

```css
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
	-moz-appearance: -moz-window-button-maximize !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-restore:not(#hack) {
	-moz-appearance: -moz-window-button-restore !important;
}
```
