### ISSUE TITLE
Installation seems to work, but theme isn't applied

### ISSUE THREAD

**Issue by FrncsCrdr** [rafaelmardojai/firefox-gnome-theme#159]
Hi,

I'm new to Linux, followed the guideline to install the theme but it didn't work.

Did this :

Clone this repo and enter folder:

git clone https://github.com/rafaelmardojai/firefox-gnome-theme/ && cd firefox-gnome-theme

Run installation script:

./scripts/install.sh # Standard

Everything seems to work, the "chrome" folder is in place (I guess)

![Capture d’écran du 2020-10-11 15-29-22](https://user-images.githubusercontent.com/72446525/95679991-a25f6600-0bd6-11eb-8eaf-71ced87b0cf2.png)

But Firefox didn't change.
What did I miss ?

**Comment by rafaelmardojai** [comment]
The chrome folder should be inside your profile folder. That should probably be cadmcxtt...

Might be some issue with the installer.

**Comment by FrncsCrdr** [comment]
Hmm ok, I deleted the chrome folder so I tried to reinstall but "git clone https://github.com/rafaelmardojai/firefox-gnome-theme/ && cd firefox-gnome-theme" doesn't work. It says that it already exists and isn't empty :(

**Comment by FrncsCrdr** [comment]
Ok, found my mistake, deleted the "firefox-gnome-theme" in my documents.
Had to move the "chrome" folder en "user.js" file to get this working. One question though, I've a GTK template that modifies the minimize, maximize and close buttons. Those your theme overwrites this ?

**Comment by rafaelmardojai** [comment]
This theme does nothing with your system. It's just CSS designed to mimic Adwaita.

**Comment by FrncsCrdr** [comment]
Yes, but I use another theme than Adwaita on my system. My system windows icons are like these : 
![image](https://user-images.githubusercontent.com/72446525/95682310-cfb31080-0be4-11eb-8801-8110bc33a9bc.png)
And the theme CSS overwrites these. Is there anything I can do to keep my themes windows icons ?

**Comment by rafaelmardojai** [comment]
Do you mean the theme overwrites your window buttons in all your desktop or only Firefox? 

If the second, that is intended since the theme styles are hardcoded. I can write a optional feature to not theme the windows buttons, so default GTK themed are used.

**Comment by FrncsCrdr** [comment]
It's the 2nd case. If it's not too long, I'd like to, to see if it's visually ok. Or maybe I just have to modify some of the .css files to get this done ?

**Comment by rafaelmardojai** [comment]
I will implement this, we already have the **System icons** optional feature, so this new **System window controls** feature will be complementary.

Something like this would make the work:
```css
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-close:not(#hack) {
	-moz-appearance: -moz-window-button-close !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-max:not(#hack) {
	-moz-appearance: -moz-window-button-maximize !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-restore:not(#hack) {
	-moz-appearance: -moz-window-button-restore !important;
}
:root[tabsintitlebar] #titlebar .titlebar-button.titlebar-min:not(#hack) {
	-moz-appearance: -moz-window-button-minimize !important;
}
```

Just need to tweak some things to fix the position of the controls.
