### ISSUE TITLE
Remove microphone privacy icon.

### ISSUE THREAD

**Issue by nickavem** [rafaelmardojai/firefox-gnome-theme#196]
I'm not sure exactly how to integrate this into this project, but I always removed the annoying microphone and camera privacy overlay icons in Firefox because they are redundant in GNOME with their own privacy icons in the top right.

The code is
```css
#webrtcIndicator {
  display: none;
}
```

and I'd love to see it integrated by default!
