### ISSUE TITLE
Bookmarks above tabs

### ISSUE THREAD

**Issue by Hasak** [rafaelmardojai/firefox-gnome-theme#223]
Is it possible to set bookmark toolbar above tabs but below main bar?

**Comment by rafaelmardojai** [comment]
It was moved under the tabs since this #211.

This should revert it: 
```css
#navigator-toolbox #PersonalToolbar {
	-moz-box-ordinal-group: 1 !important;
}
#navigator-toolbox #titlebar {
	-moz-box-ordinal-group: 2 !important;
}
```
