### ISSUE TITLE
reduce tab bar height

### ISSUE THREAD

**Issue by SilverMarcs** [rafaelmardojai/firefox-gnome-theme#232]
The current implementation of tab bar seems gigantic. Perhaps the height can be reduced for better screen estate? 
Or is it like this because it wants to be as close to gnome web as possible? if so, how do I manually reduce the tab bar height along with proper scaling of font of tab names?

**Comment by rafaelmardojai** [comment]
Yeah, it's intended to follow GNOME aesthetics.

You can set the tabs height like this:
```css
/* reduce tabs to 30px */
tab > stack {
	height: 30px !important;
	min-height: 30px !important;
}
#tabbrowser-tabs[positionpinnedtabs] > #tabbrowser-arrowscrollbox > .tabbrowser-tab[pinned] {
    min-height: 30px !important;
}
``` 

But remember that if there's a button on the tabsbar, like `Show all tabs` or `New tab`, the tabs will expand to it's height and you will also need to reduce tabsbar buttons height with this:

```css
/* 4px less than the tabs height */
#TabsToolbar .toolbarbutton-1 {
	height: 26px !important;
	max-height: 26px !important;
	min-height: 26px !important;
}
```
