### ISSUE TITLE
Tabs bar above everything

### ISSUE THREAD

**Issue by p4block** [rafaelmardojai/firefox-gnome-theme#328]
Small feature request, 

I am loving the theme and although it follows the gnome hid by placing the tab bar below the other bars, I think there should be an option to leave the tabs up top. 

It's been years of muscle memory to just slam my mouse to the top of the screen and pan in the X axis exclusively to pick a tab. _The first row of pixels on the screen should be occupied by tabs_ (mozilla devs actually broke this few times in firefox over the years in the big toolkit/theme rewrites, but it lives on)

**Comment by rafaelmardojai** [comment]
As you said, this theme follows the GNOME HIG, so that's my main focus. I can experiment with a gnomish tabs-on-headerbar pattern, but right now I have limited time to maintain this project so I can't promise anything.

I'm using/maintaining this theme since 2017, so I have a lot of muscle memory with it :P

**Comment by Commenter25** [comment]
I'm stuck with the same muscle memory of tabs on top, so I experimented around, and I created a small optional feature which accomplishes this. You can create a file named `customChrome.css` in `[firefoxprofile]/chrome/firefox-gnome-theme`, and add the codeblock below. Then, enable `gnomeTheme.tabsOnTop` just like a regular optional feature.

I've been using this about two weeks, and it seems stable enough... but I'm also the only one whose tested it, so use at your own risk? If you do see any issues, feel free to report them in this issue and I'll try to investigate. If desired, I'm willing to open a PR :)

```
@supports -moz-bool-pref("gnomeTheme.tabsOnTop") {
	/* Rearrange bars */
	#navigator-toolbox #titlebar {
		-moz-box-ordinal-group: 0;
	}
	#navigator-toolbox #nav-bar {
		-moz-box-ordinal-group: 1;
	}
	#navigator-toolbox #PersonalToolbar {
		-moz-box-ordinal-group: 2;
	}
	/* Remove nav-bar rounding */
	:root[tabsintitlebar] #navigator-toolbox > #nav-bar {
		border-radius: 0 !important;
	}
	/* Shift window controls down */
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container,
	:root[tabsintitlebar] #titlebar-buttonbox-container,
	:root[tabsintitlebar][inFullscreen] #window-controls {
		top: 38px;
	}
}
```

**Comment by Commenter25** [comment]
@emansom Here's a screenshot on a fresh profile, nothing changed except installing this theme and enabling `gnomeTheme.tabsOnTop`

![2022-08-23_12-25-47-min](https://user-images.githubusercontent.com/35016761/186225030-bb2ff0aa-e012-4ae1-8962-eface75c66e8.png)

**Comment by emansom** [comment]
> @emansom Here's a screenshot on a fresh profile, nothing changed except installing this theme and enabling `gnomeTheme.tabsOnTop`
> 
> ![2022-08-23_12-25-47-min](https://user-images.githubusercontent.com/35016761/186225030-bb2ff0aa-e012-4ae1-8962-eface75c66e8.png)

Not bad! I'll try it out!

**Comment by bbhtt** [comment]
> I'm stuck with the same muscle memory of tabs on top, so I experimented around, and I created a small optional feature which accomplishes this. 

The close button of the tab "floats" in the corner with `gnomeTheme.hideSingleTab` enabled, with this. Try opening two tabs, close one of them and see that the button is floating:

![Screenshot](https://user-images.githubusercontent.com/62639087/186439600-0f9898af-f14c-4d23-8581-ba46d9ab257f.png)

**Comment by Commenter25** [comment]
> The close button of the tab "floats" in the corner with `gnomeTheme.hideSingleTab` enabled, with this. Try opening two tabs, close one of them and see that the button is floating

This took a couple hours of experimenting and digging for obscure CSS features, but I think I worked out a solution. Along the way, I also realized this is an issue with the menu bar (which as a side effect is now on the top), and I was able to fix it while it's permanently showing. Unfortunately, there are some caveats to how I've fixed these issues.

The first is that this requires the :has pseudo-class, which was added in Firefox 103 behind the `layout.css.has-selector.enabled` flag. This puts it out of reach for anyone not on the very latest Firefox. :has seems to be the only way to climb back up the CSS tree, so without it there's no way to detect the tab or menu bar state while still reaching the window controls, breaking hideSingleTab and the menu bar. This will become less of an issue as time goes on, but it is an issue right now.

The second issue is that it doesn't render immediately, and sometimes displays double in that time; until something causes it to... "think about it" again, for a lack of better words? I'm not sure why, but I have to change the window size by ~50px for it to render the window controls in the correct position. Due to this, the menu bar still breaks window controls when temporarily bringing it up with alt. This is likely an upstream issue, especially since :has is not enabled by default yet.

Despite these issues, I have still updated the original codeblock with my changes. It should function the same as before if you don't have :has.

**Comment by bbhtt** [comment]
> This took a couple hours of experimenting and digging for obscure CSS features, but I think I worked out a solution. 

Thank you! It works but without `layout.css.has-selector.enabled`, the browser close button "floats" on the first tab (ie. when the browser is launched for the first time), opening a second tab fixes that but closing the second one makes it float again on the first tab.

**Comment by Commenter25** [comment]
I experimented with alternate solutions a bit further, and while I found and fixed some other issues (#434), unfortunately I couldn't make hideSingleTab work well without :has. I did bodge together a compromise, which accomodates both states at the same time. It will always render the window controls at the top of the window. With no tabs open, it will look normal; and with multiple tabs open, it will be uncentered next to the tabs. The nav-bar will still be padded despite having nothing in that spot.

I very heavily dislike this, to the point where I'm hesitant to post it at all. I don't think anyone would want to use it the way it is; and by default I would rather something obviously be wrong and hopefully call attention to a proper fix, than have an ugly pseudo-fix which may be shrugged off as unsolvable. But since I already took the time to figure it out and make it, and it is _technically_ better compared to drawing under the entire UI, I'm putting it here. You can add it to the end of the original code block. It will have no effect without hideSingleTab. I don't think it will be updated other than slimming it down if #434 is merged.

Because it's so close already, and I imagine someone out there will want it, I may eventually adapt this into an extra option to place window decorations back in the tab bar (almost stock firefox at that point :p), but I'll at least wait for #434 since it is heavily related

Also just to let it be known, the original code has also been updated very slightly. Nothing should visually change, just refactored a bit

<details><summary>No-Has Fallback Code</summary>

```css
	/* Fallback compromise if :has is unavailable */
	@supports not selector(:has(p)) {
		@supports -moz-bool-pref("gnomeTheme.hideSingleTab") {
			:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container {
				top: 0;
			}
			/* Pad tabs to not cover window controls */
			/* if #434 merged, replace button checks and separate variable with --gnome-navbar-csd-offset */
			@media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button), (-moz-gtk-csd-close-button) {
				:root { --gnome-tabsontop-csd-offset: 43px; }
			}
			@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button),
						 (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-close-button),
						 (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
				:root { --gnome-tabsontop-csd-offset: 78px; }
			}
			@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) and (-moz-gtk-csd-close-button) {
				:root { --gnome-tabsontop-csd-offset: 118px; }
			}
			/* Right window buttons offset by button count */
			:root[tabsintitlebar]:not([inFullscreen]) #titlebar .toolbar-items {
				padding-right: var(--gnome-tabsontop-csd-offset) !important;
			}
			/* Fullscreen headerbar padding for 1 button */
			:root[tabsintitlebar][inFullscreen] #titlebar .toolbar-items {
				padding-right: 45px !important;
			}
			/* Left window buttons */
			@media (-moz-gtk-csd-reversed-placement) {
				/* Window controls offset by button count */
				:root[tabsintitlebar]:not([inFullscreen]) #titlebar .toolbar-items {
					padding-left: var(--gnome-tabsontop-csd-offset) !important;
					padding-right: 0 !important;
				}
				/* Fullscreen headerbar padding for 1 button */
				:root[tabsintitlebar][inFullscreen] #titlebar .toolbar-items {
					padding-left: 45px !important;
					padding-right: 0 !important
				}
			}
		}
	}
```

</details>
