### ISSUE TITLE
Tabsbar: Using text colour for containers currently causes readability issues

### ISSUE THREAD

**Issue by mcrossman** [rafaelmardojai/firefox-gnome-theme#464]
![image](https://user-images.githubusercontent.com/34697309/196868366-a2f2a631-328e-460c-8813-eb029e88dda1.png)
![image](https://user-images.githubusercontent.com/34697309/196868399-37bf05d7-a707-4ebf-a8f7-103bc784e463.png)

abd0197632f27a643bde3b443dbe52c62319266d makes containers appear using text colour instead of the tab background. The current implementation has two issues:

1. Yellow containers are hard to read in light mode. There's very little contrast with the background.
2. Black/white containers are hard to distinguish from tabs that are in _no container_. In light mode, there's a colour difference (black container is quite a bit darker). In dark mode, they're identical.

The tabs in the screenshots from left to right are:

1. No container
2. Black container
3. Yellow container
4. Yellow container (active)

This happens on Firefox versions v105.0.1 and v107.0b2. It appears at commit 580bb11cd3d298b10a0cc1fc296d29d189f7a263 (latest at time of writing) and at tag `v105.1` (commit 098e3fad99685804255f27be346c477a682ebd1a).

**Comment by rafaelmardojai** [comment]
Yeah, currently we are investigating the best way of representing container tabs with the new tabs design.

Right now my idea for keeping the tab text color approach is to tweak the colors depending on dark/light and choosing a more contrasting variant of the color. The black/white case seems a bit more complex for this approach.

We're also open to new suggestions on how to represent container tabs. Tinting the tab background as before is a non-go because it makes hard to tell what tab is active.

Also I'm not sure of applying a colored line as default Firefox because it collides with the needs-attention Adwaita style.
![Captura desde 2022-10-20 07-01-48](https://user-images.githubusercontent.com/6210397/196943590-bac67b12-2d41-4c1c-92ce-40f9a2665349.png)

**Comment by TravellingGuy** [comment]
To me, changing the color of the tab text to match the container color is kind of a no go. The problem with changing the color of the tab text is with pinned tabs. Pinned tabs have no text displayed (just the favicon is displayed), so there's no way to differentiate them if just changing the text color.

**Comment by CleoMenezesJr** [comment]
All this is already taken into account. The text coloring is provisional, it was just to avoid coloring the entire tab that caused the feeling that the tab was always active.

**Comment by somepaulo** [comment]
Here's a suggestion that leaves the 'needs attention' bit alone (at least until that sets a different background to the same UI element) and makes container tabs visible again. Looks like this:

![Screenshot from 2022-11-19 22-34-39](https://user-images.githubusercontent.com/15643750/202874211-6ab46bc3-b579-479f-a306-566fa9751b43.png)

Works like this:
```css
/* Create new container tab indicator */
.tabbrowser-tab[class*="identity-color-"] .tab-label-container {
	/* color: var(--identity-tab-color) !important; */
	color: var(--gnome-toolbar-color) !important;
}

.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content {
  background-image: radial-gradient(var(--identity-tab-color) 50%, var(--identity-tab-color) 50%) !important;
  background-position: center 1px !important;
	background-size: 100% 4px !important;
	background-repeat: no-repeat;
	border-radius: 7px;
}
```

These look better in the bottom, IMHO. And the 'needs attention' line is barely visible anyway, especially when you have many tabs with text. That thin line of colour gets lost, so personally I'd go for colour lines on the bottom, but that's just me.

**Comment by Draculah** [comment]
It appears this yellow text on the tabs in light theme is still the current behavior, so I looked around and found this issue.

As no solution has been picked yet, I propose something like the following solution.

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/73490292/b439b481-37e8-4577-889f-e5911032c939)

Here I made a distinction between active tabs having a long bar and the other tabs with a small bar. I felt the long bars of the previous solution by @somepaulo were a good, decent attempt, and much better than the default, but having the long bars on every tab is distracting and makes it harder to distinguish the active tab quickly. The downside now is that it's slightly harder to see which container a non-active tab belongs to.

It annoys me however that the background bar of the container still gets slightly faded out (as can be noticably seen in the active tab of the bigger window), hence large gaps on the left and the right for the active tab bar. I felt it should be centered, so if the right side gets faded out too much, it looks off, so I just shrunk it. Personally, I think something like `calc(100% - 64x)` would have been okay for the background size, but then it's already very visible. I hope anyone else knows how to fix that.

Do note that I did not bother to add an extra rule for the pinned tabs that are selected. They will now have no bar upon select, but this is merely a proof of concept.

I pasted this in my `chrome/userChrome.css` to override the current theming done by firefox-gnome-theme:

```css
/* Create new container tab indicator */
.tabbrowser-tab[class*="identity-color-"] .tab-label-container {
	/* color: var(--identity-tab-color) !important; */
	color: var(--gnome-toolbar-color) !important;
}

.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content {
  background-image: radial-gradient(var(--identity-tab-color) 50%, var(--identity-tab-color) 50%) !important;
  background-position: center bottom !important;
  background-size: 8px 2px !important;
  background-repeat: no-repeat;
  border-radius: 5px;
}

.tabbrowser-tab[class*="identity-color-"][selected="true"] > .tab-stack > .tab-content {
  background-size: calc(100% - 80px) 2px !important;
}

/* Needs attetion tab indicator */
.tabbrowser-tab:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"]),
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]) {
	/* background-image: radial-gradient(var(--gnome-tabbar-tab-needs-attetion), var(--gnome-tabbar-tab-needs-attetion) 10px) !important; */
	background-image: radial-gradient(var(--gnome-tabbar-tab-needs-attetion) 50%, var(--gnome-tabbar-tab-needs-attetion) 50%) !important;
	/* background-position: center bottom !important;
	background-size: 14px 2px !important; */
}
.tabbrowser-tab[class*="identity-color-"]:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"]),
.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]) {
  background-image: radial-gradient(var(--gnome-tabbar-tab-needs-attetion) 50%, var(--identity-tab-color) 50%) !important;
}
```

Hope this yellow text on white background gets resolved soon! :-)

Btw, perhaps it's also an option to simply alter the container-tab-colors to be more contrasting through css? (A more clear tint of yellow on white for example.) I found this, [here](https://github.com/mozilla/multi-account-containers/issues/391#issuecomment-368238595):

```css
[data-identity-color="red"] {
  --identity-tab-color: #000000 !important;
  --identity-icon-color: #000000 !important;
}
```

**Comment by rafaelmardojai** [comment]
@Draculah, IMO the underline is the best solution, but as stated before, it collides with the libadwaita's needs attention style.

**Comment by Draculah** [comment]
So, I may not be completely following, I misunderstood before - well, I think - that the "needs attention style" was a guideline. Or perhaps it _is_ css written by this project, but there is no way to combine the css and the underline. Whatever the case, I will not investigate it, as I'm not a css expert and someone else will have more knowledge about it, so I'd only waste time.

I think the current yellow on white is problematic and the Flathub app Contrast agrees :-)

![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/73490292/b18fea1f-d100-4219-8d53-fd1bfc3a5abc)

I also see that you already pointed out that you are looking into using different variants of the colors. Are you still?

> Right now my idea for keeping the tab text color approach is to tweak the colors depending on dark/light and choosing a more contrasting variant of the color.

I'll use the custom underline for now, as long as the colors aren't contrasting enough, but I can look into variants of the colors if you haven't found enough time doing so. Can I track your attempts somewhere?

**Comment by CleoMenezesJr** [comment]
This is a problem we are aware of and has been discussed. This solution you proposed, I had already implemented it as a pseudo solution, but the conclusion was the same: it clashes with "needs attention". The solution that I believe works the most would be to add shadow to the letters. But dunno...

**Comment by rafaelmardojai** [comment]
> So, I may not be completely following, I misunderstood before - well, I think - that the "needs attention style" was a guideline. Or perhaps it is css written by this project, but there is no way to combine the css and the underline. Whatever the case, I will not investigate it, as I'm not a css expert and someone else will have more knowledge about it, so I'd only waste time.

The thing is that we mimic the libadwaita styling. Libadwaita uses a blue underline inside tabs when they need attention.

Like this:
![Captura desde 2023-06-23 12-07-14](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/fb7dd1f7-2eac-4b3d-b16b-ba64f7481cfa)

So in short, the underline is already used for needs-attention tabs and we need to figure out another way. We need to implement a design that plays along with how libadwaita looks. 

> I also see that you already pointed out that you are looking into using different variants of the colors. Are you still?

Yes, it is planned but I didn't have time. The idea is to use colors from the GNOME palette for light and dark theme that have good contrast.

**Comment by rafaelmardojai** [comment]
I have introduced custom colors and bold font to the container tabs that hopefully improves readability.

#### Before:
![Captura desde 2023-07-15 22-38-53](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/1136eb51-43c9-4507-a11e-ce5b6ee4ab1d)
![Captura desde 2023-07-15 22-39-02](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/78e826cd-2bf1-488b-9aa7-86e08c24266b)

#### After:
![Captura desde 2023-07-15 22-39-19](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/8482c4bf-1a50-48b2-99d3-0bfa3bbe302e)
![Captura desde 2023-07-15 22-39-25](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/6210397/a3300f98-0310-4d09-8de0-e097ea0453ce)

**Comment by somepaulo** [comment]
The final adopted solution doesn't work for me, so I stick with using a thick bottom underline with the container colour. I went ahead and accommodated for the "needs attention" line to overlay it on top of the container colour. 
![tab-group-attention](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/15643750/18226610-154a-4414-89f4-43affcc9a7e9)

![Screenshot from 2023-08-03 01-00-04](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/15643750/c8486493-01be-4b39-9c61-519356526bb3)

Here's the code that I use. Feel free to use it in any way you like.

```css
/* Tab containers */
.tabbrowser-tab[usercontextid] > .tab-stack > .tab-background > .tab-context-line {
	display: none;
}

.tabbrowser-tab[class*="identity-color-"] .tab-label-container {
	color: var(--gnome-toolbar-color) !important; /*color: var(--identity-tab-color) !important;*/
	font-weight: normal !important; /*font-weight: bold !important;*/
}

.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content {
  background-image: radial-gradient(var(--identity-tab-color) 50%, var(--identity-tab-color) 50%) !important;
  background-position: center bottom !important;
	background-size: 100% 4px !important;
	background-repeat: no-repeat;
	border-radius: 5px;
}

/* Needs attetion tab indicator */
.tabbrowser-tab:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"]),
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]) {
	background-image: radial-gradient(var(--gnome-tabbar-tab-needs-attetion), var(--gnome-tabbar-tab-needs-attetion) 10px) !important;
	background-position: center bottom !important;
	background-size: 14px 2px !important;
}

.tabbrowser-tab[class*="identity-color-"]:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"]),
.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]) {
	background-image: radial-gradient(circle at 50% 100%, transparent 7px, transparent 7px, var(--identity-tab-color) 27px) !important;
	background-position: center bottom !important;
	background-size: 100% 4px !important;
}

.tabbrowser-tab[class*="identity-color-"]:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"])::after,
.tabbrowser-tab[class*="identity-color-"] > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"])::after {
  display: block;
  position: absolute;
  left: 0;
  bottom: 0;
  width: 100%;
  height: 2px;
  content: ' ';
	background-image: radial-gradient(circle at 50% 100%, var(--gnome-tabbar-tab-needs-attetion) 7px, transparent 7px) !important;
	background-position: center bottom !important;
}
```
