### ISSUE TITLE
The theme not handling responsive

### ISSUE THREAD

**Issue by kenso312** [rafaelmardojai/firefox-gnome-theme#590]
**Describe the bug**
Some buttons do not display well in small window sizes.

**To Reproduce**

[before-with-title-bar](https://user-images.githubusercontent.com/82863124/230929364-3490415e-2c0d-4967-9b7d-4c5d2bc38a19.webm)

[before](https://user-images.githubusercontent.com/82863124/230925203-558079fb-d612-414e-9368-10d3c3dc01a3.webm)

**Expected behavior**
Following Firefox's default behavior, the button should disappear if the width of the window size does not have enough space.

**Setup information**
 - OS: Ubuntu, Pop!_OS
 - Installation method: APT, raw download (developer version)
 - Firefox version: 111, 112
 - Theme version: v111

**Additional context**

I try to fix this by adding the below code, which can simulate the fully responsive behavior like Firefox well but not sure if that is a good way or not since the code is a bit mazy. Thanks.
 
```css
/* Enable title bar */
@media (max-width: 470px) {
  #nav-bar-overflow-button {
    -moz-window-dragging: drag !important;
    visibility: hidden !important;
  }
}

/* Disable title bar + enable close button only  */
@media not ((-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button)) {
  @media (max-width: 570px) {
    :root[tabsintitlebar] #nav-bar-overflow-button {
      display: none !important;
    }
  }

  @media (max-width: 475px) {
    :root[tabsintitlebar] #unified-extensions-button {
      display: none !important;
    }
  }
}

/* Disable title bar + enable either minimize or maximize button  */
@media (-moz-gtk-csd-minimize-button), (-moz-gtk-csd-maximize-button) {
  @media (max-width: 615px) {
    :root[tabsintitlebar] #nav-bar-overflow-button {
      -moz-window-dragging: drag !important;
      visibility: hidden !important;
    }
  }

  @media (max-width: 580px) {
    :root[tabsintitlebar] #unified-extensions-button {
      display: none !important;
    }
  }

  @media (max-width: 475px) {
    :root[tabsintitlebar] #PanelUI-button {
      display: none !important;
    }
  }
}

/* Disable title bar + enable both minimize and maximize button  */
@media (-moz-gtk-csd-minimize-button) and (-moz-gtk-csd-maximize-button) {
  @media (max-width: 645px) {
    :root[tabsintitlebar] #nav-bar-overflow-button {
      -moz-window-dragging: drag !important;
      visibility: hidden !important;
    }
  }

  @media (max-width: 610px) {
    :root[tabsintitlebar] #unified-extensions-button {
      -moz-window-dragging: drag !important;
      visibility: hidden !important;
    }
  }

  @media (max-width: 575px) {
    :root[tabsintitlebar] #PanelUI-button {
      display: none !important;
    }
  }

  @media (max-width: 475px) {
    :root[tabsintitlebar] #reload-button {
      display: none !important;
    }
  }
}
```

[after-no-title-bar](https://user-images.githubusercontent.com/82863124/230930253-178aea84-f96a-460d-81f8-17b07d40fc31.webm)

[after-1-btn](https://user-images.githubusercontent.com/82863124/230930311-51a9aaeb-e2f9-4395-8257-0e506062c729.webm)

[after-2-btn](https://user-images.githubusercontent.com/82863124/230930346-5bb3dc03-0394-4c82-8af4-29769bca8ad2.webm)

[after-3-btn](https://user-images.githubusercontent.com/82863124/230930385-eae5030e-4de8-4911-bbf7-94b71ee867ae.webm)

<br>

In some sections I use visibility hidden instead of display none is to prevent icon flickering (like below [Random User Agent](https://addons.mozilla.org/en-US/firefox/addon/random_user_agent/) icon), also have some extra space is easier to drag the window.

[after-with-display-none.webm](https://user-images.githubusercontent.com/82863124/230932398-def804d0-009f-482e-a50c-c39f617f2bc5.webm)
