### ISSUE TITLE
Context menu buttons and autofill styling

### ISSUE THREAD

**Issue by 7xa5h** [rafaelmardojai/firefox-gnome-theme#651]
**Describe the bug**

The buttons dont have icons and arent symmetrically rounded and the autofill doesnt have styling
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/119355463/125747f5-fb77-4440-972d-76d8ed8c5680)
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/119355463/cfb70548-c48a-4272-9c29-eec185c04cab)

**To Reproduce**

**Setup information**
 - OS: Windows (I know its not supported but oh well)
 - Installation method: Manual
 - Firefox version: 115
 - Theme version: 115
 - Optional features enabled: Idk but i disabled csd.css

**Comment by 7xa5h** [comment]
and yes, even after enabling csd.css the same issue occurs, i do have all the icons at the correct path and every other part of the theme works fine

**Comment by Masellum** [comment]
For the buttons, add the following lines to userChrome.css:
```css
@media (-moz-windows-non-native-menus) {
  #context-navigation > .menuitem-iconic > .menu-iconic-left > .menu-iconic-icon {
    padding: 0px 0em !important;
  }
}
```
This solved the problem for me (though there might be more elegant method). I'm using Firefox 116 BTW.
