### ISSUE TITLE
Tabs bar overflow arrows invisible

### ISSUE THREAD

**Issue by somepaulo** [rafaelmardojai/firefox-gnome-theme#749]
**Describe the bug**
The tabs bar overflow arrows have disappeared a couple of updates ago.

**To Reproduce**
1. Open enough tabs to overflow the tabs bar.
2. Look for overflow arrows on either side of the tabs bar.
3. Not see them.

**Expected behavior**
When the tabs bar overflows, arrows should appear on either side of the tabs bar (except the side that is fully scrolled to an end).

**Screenshots**
How it is
![Screenshot from 2024-01-17 12-07-41](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/15643750/4511bd26-9184-451e-8d10-c925d23b5902)

How it should be
![Screenshot from 2024-01-17 12-07-53](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/15643750/b4c12fb4-a893-4c7d-9c58-9fa261f3ccb1)

**Setup information**
 - OS: Arch
 - Installation method: manual
 - Firefox version: 121.0.1
 - Theme version: master
 - Optional features enabled: none

**Additional context**
The CSS applied to the arrow images (in `tabsbar.css`, line 59) is still used when the arrows should be displayed:
```css
#scrollbutton-up:has(~ .scrollbox-clip[orient="horizontal"]) > .toolbarbutton-icon, .scrollbox-clip[orient="horizontal"] ~ #scrollbutton-down > .toolbarbutton-icon {
  visibility: hidden;
}
```

Adding this solves it for me:
```css
#scrollbutton-up:has(~ .scrollbox-clip[orient="horizontal"]):not([disabled]) > .toolbarbutton-icon, .scrollbox-clip[orient="horizontal"] ~ #scrollbutton-down:not([disabled]) > .toolbarbutton-icon {
  visibility: visible;
}
```
