### ISSUE TITLE
tabbar title

### ISSUE THREAD

**Issue by paulocanedo** [rafaelmardojai/firefox-gnome-theme#75]

**Comment by paulocanedo** [comment]
I really didn't like the tabbar title as bold, could you provide some config to disable it?

**Comment by rafaelmardojai** [comment]
You can easily modify the theme adding your code to the `UserChrome.css` file.

This selectors should help you to get the job done:
```css
tab {
	font-weight: normal !important;
}
tab:hover {
}
tab[selected] {
}
tab:-moz-window-inactive {
}
tab[selected]:-moz-window-inactive {
}
```
