### ISSUE TITLE
Sharp corners

### ISSUE THREAD

**Issue by Articmar** [rafaelmardojai/firefox-gnome-theme#762]
For several versions in a row now, the theme has been setting up sharp corners for LibreWolf. 

![screen](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/118318866/7dd2163a-8430-439a-afc4-d672e50a2e1c)

Current setup:
- Fedora Linux 39 (Workstation Edition) 
- GNOME: 45.4 (Wayland) 
- Linux 6.7.9-200.fc39.x86_64 
- LibreWolf 123.0-1 (Flatpak)
- Theme v122

**Comment by abdmoh123** [comment]
A temporary workaround is to edit `firefox-gnome-theme/theme/pars/csd.css`.

Change
```
/* Headerbar top border corners rounded */
:root[tabsintitlebar][sizemode="normal"]:not([gtktiledwindow="true"]) #nav-bar {
	border-radius: env(-moz-gtk-csd-titlebar-radius) env(-moz-gtk-csd-titlebar-radius) 0 0 !important;
}
```

to
```
/* Headerbar top border corners rounded */
:root[tabsintitlebar][sizemode="normal"]:not([gtktiledwindow="true"]) #nav-bar {
	border-radius: 8px 8px 0 0 !important;
}
```

**Comment by rafaelmardojai** [comment]
Hmm, if `-moz-gtk-csd-titlebar-radius` not existing in LibreWolf is the problem I guess it could be fixed in the theme with a `env()` fallback value:

```css
:root[tabsintitlebar][sizemode="normal"]:not([gtktiledwindow="true"]) #nav-bar {
	border-radius: env(-moz-gtk-csd-titlebar-radius, 8px) env(-moz-gtk-csd-titlebar-radius, 8px) 0 0 !important;
}
```

Please test if that works.
