### ISSUE TITLE
Window controls missing on macOS

### ISSUE THREAD

**Issue by qwertychouskie** [rafaelmardojai/firefox-gnome-theme#773]
**Describe the bug**
Window controls are missing on macOS.

**To Reproduce**
Install theme on macOS

**Expected behavior**
Window controls exist

**Screenshots**
<img width="1728" alt="image" src="https://github.com/rafaelmardojai/firefox-gnome-theme/assets/13989090/60480f15-c284-4a6f-9f1f-f9f387b041ec">

**Setup information**
 - OS: macOS 14.4.1
 - Installation method: Manual
 - Firefox version: 124.0.2
 - Theme version: master
 - Optional features enabled: gnomeTheme.bookmarksToolbarUnderTabs = true, gnomeTheme.normalWidthTabs = true

**Additional context**
Sadly I have to use macOS for work

**Comment by rafaelmardojai** [comment]
Looking at https://github.com/mozilla/gecko-dev/blob/f602853ba8d55ba157e2a74d9b571615f6ed97b8/layout/style/test/chrome/chrome-only-media-queries.js looks like we might have some alternatives.

Can you check if the following code works?

```css
@media (-moz-platform: macos) {
	:root {
		--gnome-navbar-csd-offset: 117px;
	}
	:root[tabsintitlebar]:not([inFullscreen]) #nav-bar {
		padding-left: var(--gnome-navbar-csd-offset) !important;
		padding-right: 3px !important;
	}
	:root[tabsintitlebar] #titlebar .titlebar-buttonbox-container {
		left: 0;
		right: auto !important;
	}
}
```
