### ISSUE TITLE
[Vertical tab - Extension] Sidebar flickering in fullscreen mode

### ISSUE THREAD

**Issue by lukas-kasticky** [rafaelmardojai/firefox-gnome-theme#797]
**To Reproduce**

1. Go to YouTube or any video other video
2. Put it on fullscreen
4. See flickering sidebar

**Expected behavior**

Sidebar hides (maybe configurable?)

**Screenshots**

![Had to take a video to get that screenshot](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/20475412/757943e2-8c6a-4ccf-abbb-d8e6c764aecd)

**Setup information**

 - OS: openSUSE Aeon
 - Installation method: Flatpak
 - Firefox version: Librewolf 126.0-1
 - Theme version: master
 - Optional features enabled:
     - `gnomeTheme.extensions.tabCenterReborn` `true`
     - `gnomeTheme.extensions.tabCenterReborn.alwaysOpen` `true`
     - `gnomeTheme.hideSingleTab` `true`
     - `gnomeTheme.symbolicTabIcons` `true`
     - `gnomeTheme.extensions.tabCenterReborn` `true`
     - `gnomeTheme.extensions.tabCenterReborn.alwaysOpen` `true`

**Additional context**

Found the following snippet [in the wiki](https://framagit.org/ariasuni/tabcenter-reborn/-/wikis/home#hide-sidebar-in-fullscreen), but it doesn't improve anything.

```css
#main-window[inFullscreen="true"] #sidebar-box[sidebarcommand="tabcenter-reborn_ariasuni-sidebar-action"],
#main-window[inFullscreen="true"] #sidebar-box[sidebarcommand="tabcenter-reborn_ariasuni-sidebar-action"] + splitter {
    visibility: collapse;
}
```
