### ISSUE TITLE
[Feature] bookmarks bar density? padding/margin

### ISSUE THREAD

**Issue by AskAlice** [rafaelmardojai/firefox-gnome-theme#810]
**Is your feature request related to a problem? Please describe.**

Love the theme, but the padding on bookmark bar buttons is too high, and not sure if necessary but i feel like i might need to tweak the margin as well. Compared to chrome it only contains about 60% of the bookmarks i use on a daily basis, Not sure if it matters but most of my bookmarks are organized without a title just the favicon.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AskAlice** [comment]
![image](https://github.com/rafaelmardojai/firefox-gnome-theme/assets/1855905/b9abd68e-6321-4bd6-bd0d-351b7652b253)

**Comment by rafaelmardojai** [comment]
Right now we use the GNOME buttons spacing, but I guess we could try to make it more compact.

**Comment by AskAlice** [comment]
> Right now we use the GNOME buttons spacing, but I guess we could try to make it more compact.

hmm yeah i was looking through the CSS and the only reason I made a ticket was because I'm not sure where the class names/css selectors are documented (like if you hit ctrl+shift+c on a webpage then click an element)

**Comment by AskAlice** [comment]
I tried using all of these, seems there's something more to it than  this /shrug

```css

/* Bookmark buttons */
#nav-bar toolbarbutton.bookmark-item {
	width: auto !important;
	padding: 0px !important;
	margin: 0px !important;
}
#nav-bar button.bookmark-item {
	padding: 0px;
	margin: 0px;
}
#nav-bar toolbarbutton.bookmark-item .toolbarbutton-icon {
	padding: 0 !important;
	margin: 0 !important;
}
#nav-bar toolbarbutton.bookmark-item .toolbarbutton-text {
	padding: 0 !important;
	margin: 0 !important;
}
#nav-bar toolbarbutton{
	padding: 0 !important;
}
```
