### ISSUE TITLE
[Feature] Native vertical tabs

### ISSUE THREAD

**Issue by reesericci** [rafaelmardojai/firefox-gnome-theme#820]
**Is your feature request related to a problem? Please describe.**

Firefox has rolled out vertical tabs natively in nightly and I'd like it if this theme would support them. https://connect.mozilla.org/t5/discussions/firefox-sidebar-and-vertical-tabs-try-them-out-in-nightly/td-p/63231

**Describe the solution you'd like**

Styling similar to the tab center reborn integration

**Describe alternatives you've considered**

**Additional context**

**Comment by Tuxino88** [comment]
![Schermata del 2024-10-09 11-43-00](https://github.com/user-attachments/assets/68146bc6-50fe-44be-b55e-ff286fc44082)

bad support

**Comment by rafaelmardojai** [comment]
> bad support

There's an initial theming for the sidebar in the nightly branch, but vertical tabs are not supported yet.

**Comment by RushingAlien** [comment]
Hey :wave:, as of firefox stable release 133, vertical tabs are now supported  
![image](https://github.com/user-attachments/assets/1cdb6c4c-3f6c-4b2e-b4ff-1bd8d751f68d)

**Comment by RushingAlien** [comment]
![gambar](https://github.com/user-attachments/assets/85267eff-2406-49a2-ab34-1644e9fe20d7)

I think tabs close button should be disabled in vertical?

**Comment by malobre** [comment]
@rafaelmardojai FYI, `sidebar.revamp` was enabled for some users with the 133 update and it will be expanded to another "portion of users" in 134.

See this [Mozilla Connect Discussion](https://connect.mozilla.org/t5/discussions/sidebar-and-vertical-tabs-release-channel-experimentation/td-p/78966).

ps: love the theme ! Thank you for all your hard work.

**Comment by rodrigost23** [comment]
Vertical tabs are already generally available in Firefox 136: https://www.mozilla.org/en-US/firefox/136.0/releasenotes/

**Comment by Joseph-DiGiovanni** [comment]
The theme currently seems to break scrolling of the vertical tabs sidebar if you have many open as well.

**Comment by ai** [comment]
On open mode right now there is a problem with shadow and margins

![Image](https://github.com/user-attachments/assets/4b69dd93-430b-414c-86dd-cb973261942a)

Collapsed form have more issues.

**Comment by ai** [comment]
Here is my fix for open form (very dirty)

```css
.tab-background {
    &:is([selected], [multiselected]) {
        box-shadow: none !important;
    }
}

#vertical-pinned-tabs-container {
    padding-inline: 0 !important;
}
#tabbrowser-tabs[orient="vertical"] {
    & .tab-background {
        margin-inline: 6px !important;
    }
}
.tab-content {
    padding-inline: 18px !important;
}

#tabbrowser-tabs[orient="vertical"] {
    & .tabbrowser-tab {
        &:nth-child(1 of :not([hidden])) {
            padding-block-start: 0 !important;
        }
    }
}

#tabbrowser-arrowscrollbox[orient="vertical"]
    > #tabbrowser-arrowscrollbox-periphery
    > #tabs-newtab-button,
#vertical-tabs-newtab-button {
    margin-inline: 6px !important;
    padding-inline: 12px !important;
}
```

I also made grayscaled icons for extensions below:

```css
.tools-and-extensions[orientation="horizontal"] moz-button[extensionId] {
    filter: grayscale(1) contrast(130%) !important;
}
```
