### ISSUE TITLE
[Fixed] "close button overlay" offset

### ISSUE THREAD

**Issue by Acumane** [rafaelmardojai/firefox-gnome-theme#897]
The linear gradient behind the tab close button is offset. Repro'ed in at least `134.0` and `133.1`

![image](https://github.com/user-attachments/assets/d50a7fa2-adf5-445e-a242-b57cf8cc8c81)

Fixed @ `tabsbar.css:276`:

```css
/* Close button overlay */
&:not([pinned])::before {
	background: linear-gradient(to left, var(--gnome-tabbar-tab-close-overlay-bg) 50%, transparent);
	border-radius: 0 6px 6px 0;
	content: "";
	height: 100%;
	opacity: 0;
	position: absolute;
	right: 0px;
	transition: background 0.4s linear;
	width: 55px;
	z-index: 99;
}
```
