### ISSUE TITLE
Firefox 136 Theme Issues

### ISSUE THREAD

**Issue by KUPOinyourWINDOW** [rafaelmardojai/firefox-gnome-theme#909]
There's a few this time unfortunately.

1) Tab text and icons seems incorrectly aligned, like its shifted to the right slightly

2) Tab close button is too small

3) Tab audio playing mute button has incorrect highlight when you move your mouse over the button

![Image](https://github.com/user-attachments/assets/07ba4528-2d6e-45d1-ac4f-c17b1ab13b92)

**Comment by rafaelmardojai** [comment]
So they now use a `<html:moz-button>` for the mute icon, which uses shadow DOM. I've been working-around shadow DOM styling in various ways in the past years, but in this case I think we have reached the limit.  `<html:moz-button>` is pretty generic, and I wouldn't be able to distinguish between the tab mute button or a toolbar close button.

The root of the problem is that the mechanics to property select shadow DOM elements like [`:host()`](https://developer.mozilla.org/en-US/docs/Web/CSS/:host_function) and [`::part()`](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) aren't allowed for "user" stylesheets, which is the case of `customChrome.css`. See Firefox [bug 1575507](https://bugzilla.mozilla.org/show_bug.cgi?id=1575507) for more info.

So, honestly, this could be the end of this theme, or a point that would require various changes, like the way it's installed. We'll need to add an author stylesheet loader, that means that we'll need to add files to the Firefox installation folder, like we did for the [firefox-gnome-scrollbars](https://github.com/rafaelmardojai/firefox-gnome-scrollbars) years ago. And I'm not sure if that will be posible with Flatpak, which would be discouraging for me.

**Comment by juxuanu** [comment]
Would the solution be https://github.com/rafaelmardojai/firefox-gnome-theme/issues/353?

**Comment by Subwaytime** [comment]
Might be not a perfect fix, but here is a small workaround (for the close button)

```css
tabs#tabbrowser-tabs {
  &[orient="horizontal"] {
    & tab {
      & .tab-content {
        & .tab-close-button {
          height: 24px !important;
          width: 24px !important;
        }
      }
    }
  }
}
```
