### ISSUE TITLE
Confirm close alert at bottom on MacOS

### ISSUE THREAD

**Issue by werunthenite** [rafaelmardojai/firefox-gnome-theme#93]
Sorry for my poor English, here's an screen record:

![Untitled](https://user-images.githubusercontent.com/8917663/68433981-75f8c980-017d-11ea-9327-35b7622e21e1.gif)

**Comment by rafaelmardojai** [comment]
Interesting to see somebody using this theme on MacOS.

That wrong behavior does not happens in default Firefox (without theme)?

**Comment by werunthenite** [comment]
> Interesting to see somebody using this theme on MacOS.
> 
> That wrong behavior does not happens in default Firefox (without theme)?

I don't like Firefox default theme, that's why I use this one.

And no, that doesn't happen without gnome theme.

<img width="1680" alt="Captura de Pantalla 2019-11-07 a la(s) 21 17 29" src="https://user-images.githubusercontent.com/8917663/68447018-119d3080-01a4-11ea-8200-3ccd78e3a349.png">

**Comment by rafaelmardojai** [comment]
Es un comportamiento extraño, lo unico que modifica este tema en los dialogos son los botones.

Te adjunto una version modificada de `/theme/parts/buttons.css` sin soporte a `.dialog-button` para ver si eso es lo que causa el problema.

```css
/* Buttons */
@import "buttons-fixes.css";
@namespace xul "http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul";

/* Hide buttons separator */
#nav-bar .toolbaritem-combined-buttons separator {
	display: none !important;
}
#appMenu-popup .toolbaritem-combined-buttons toolbarseparator {
	border: 0 !important;
}

/* Buttons */
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton),
.subviewbutton.panel-subview-footer,
.panel-footer button,
#downloadsHistory,
#downloadsPanel-mainView .download-state .downloadButton,
#overflowMenu-customize-button,
#appMenu-popup .panel-banner-item,
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not(#appMenu-fxa-label),
.subviewbutton-back,
#context-navigation menuitem,
.identity-popup-preferences-button:not(#hack),
.findbar-container toolbarbutton,
#sidebar-switcher-target,
#viewButton,
.close-icon:not(.tab-close-button),
#TabsToolbar .toolbarbutton-1,
.menulist-label-box,
.expander-down, .expander-up,
.notification-button,
.protections-popup-footer-button,
.identity-popup-permission-remove-button,
#identity-popup-security-expander,
#PanelUI-panic-view-button,
.tracking-protection-button {
	-moz-appearance: none !important;
	background: var(--gnome-button-background) !important;
	box-shadow: var(--gnome-button-box-shadow) !important;
	border: 1px solid var(--gnome-button-border-color) !important;
	border-bottom-color: var(--gnome-button-border-accent-color) !important;
	border-radius: 5px !important;
	padding: 0 3px !important;
	height: 34px !important;
	max-height: 34px !important;
	min-height: 34px !important;
	min-width: 34px !important;
	color: var(--gnome-toolbar-color) !important;
	font: menu !important;
}

/* Buttons with margins */
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton),
.notification-button {
	margin: 0 3px !important;
}
#TabsToolbar .toolbarbutton-1 {
	margin: 2px 3px !important;
}
.close-icon:not(.tab-close-button) {
	margin-left: 6px !important;
}

/* Text buttons */
.subviewbutton.panel-subview-footer,
.panel-footer button,
#downloadsHistory,
#overflowMenu-customize-button,
#appMenu-popup .panel-banner-item,
#appMenu-zoomReset-button:not(#appMenu-fxa-label):not(#hack),
#tracking-protection-preferences-button:not(#hack),
.findbar-container toolbarbutton.findbar-button,
.notification-button,
.protections-popup-footer-button,
#PanelUI-panic-view-button,
.tracking-protection-button {
	padding: 2px 16px !important;
	text-align: center !important;
}
.subviewbutton.panel-subview-footer label {
	text-align: center !important;
}

/* Drop down buttons */
#sidebar-switcher-target,
#viewButton {
	padding: 2px 16px !important;
	position: relative;
}
#sidebar-switcher-arrow,
#viewButton .button-menu-dropmarker { /* Arrow position, type b */
	transform: translate(6px, 0)
}
.menulist-label-box {
	padding: 2px 26px 2px 16px !important;
	position: relative;
}
.menulist-label-box:after { /* Arrow position */
	position: absolute !important;
	right: 8px !important;
	top: 8px !important;
}
.menulist-label-box:after { /* Create arrow if icon tag no exist */
	content: "";
}

/* Hover buttons */
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not([open]):not([disabled]):not([checked]):hover,
.subviewbutton.panel-subview-footer:hover,
.panel-footer button:hover,
#downloadsHistory:hover,
#downloadsPanel-mainView .download-state .downloadButton:hover,
#overflowMenu-customize-button:hover,
#appMenu-popup .panel-banner-item:hover,
.subviewbutton-back:hover,
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not(#appMenu-fxa-label):not([disabled]):hover,
#context-navigation menuitem:not([disabled]):hover,
.identity-popup-preferences-button:not(#hack):hover,
.findbar-container toolbarbutton:hover,
.findbar-closebutton .toolbarbutton-icon:hover,
#sidebar-switcher-target:hover,
#viewButton:hover,
.close-icon:not(.tab-close-button):hover,
#TabsToolbar .toolbarbutton-1:hover,
menulist:hover .menulist-label-box,
.expander-down:hover, .expander-up:hover,
.notification-button:hover,
.protections-popup-footer-button:hover,
.identity-popup-permission-remove-button:hover,
#identity-popup-security-expander:hover,
.tracking-protection-button:hover {
	outline: 0 !important;
	background: var(--gnome-button-hover-background) !important;
}

/* Active buttons */
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not([disabled]):not(#hack):active,
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not(.subviewbutton):not([disabled])[open],
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):not([disabled])[checked],
.subviewbutton.panel-subview-footer:active,
.panel-footer button:active,
#downloadsHistory:active,
#downloadsPanel-mainView .download-state .downloadButton:active,
#overflowMenu-customize-button:active,
#appMenu-popup .panel-banner-item:active,
.subviewbutton-back:not(#hack):active,
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not([disabled]):not(#appMenu-fxa-label):active,
#context-navigation menuitem:active:not([disabled]),
.identity-popup-preferences-button:not(#hack):active,
.findbar-container toolbarbutton[checked],
.findbar-container toolbarbutton:active,
#sidebar-switcher-target:active, #sidebar-switcher-target.active,
#viewButton[open],
.close-icon:not(.tab-close-button):active,
#TabsToolbar .toolbarbutton-1:active, #TabsToolbar .toolbarbutton-1[open],
menulist[open] .menulist-label-box,
.expander-down:active, .expander-up:active,
.notification-button:active,
.protections-popup-footer-button:not(#hack):active,
.identity-popup-permission-remove-button:active,
#identity-popup-security-expander:active,
.tracking-protection-button:active {
	background: var(--gnome-button-active-background) !important;
	box-shadow: var(--gnome-button-active-box-shadow) !important;
	border-color: var(--gnome-button-active-border-color) !important;
	border-bottom-color: var(--gnome-button-active-border-color) !important;
	border-top-color: var(--gnome-button-active-border-accent-color) !important;
}

/* Disabled buttons */
#nav-bar toolbarbutton:not(#urlbar-zoom-button)[disabled],
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton[disabled],
#context-navigation menuitem[disabled] {
	background: var(--gnome-button-disabled-background) !important;
	border-color: var(--gnome-button-disabled-border-color) !important;
	box-shadow: var(--gnome-button-disabled-box-shadow) !important;
	opacity: 1 !important;
}
#nav-bar toolbarbutton:not(#urlbar-zoom-button)[disabled] image,
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton[disabled] image,
#context-navigation menuitem[disabled] image {
	opacity: .4 !important;
}

#nav-bar toolbarbutton:not(#urlbar-zoom-button)[disabled]:hover,
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton[disabled]:hover {
	background: var(--gnome-button-disabled-background) !important;
}

/* Inactive window buttons */
#nav-bar toolbarbutton:not(#urlbar-zoom-button):not(.subviewbutton):-moz-window-inactive,
.findbar-container toolbarbutton:-moz-window-inactive,
#sidebar-switcher-target:-moz-window-inactive,
#viewButton:-moz-window-inactive,
.notification-button:-moz-window-inactive {	
	background: var(--gnome-inactive-button-background) !important;
	box-shadow: var(--gnome-inactive-button-box-shadow) !important;
	border-color: var(--gnome-inactive-button-border-color) !important;
}

/* Flat buttons */
.subviewbutton-back:not(#hack),
.close-icon:not(.tab-close-button),
#TabsToolbar .toolbarbutton-1,
#protections-popup-show-report-button,
.identity-popup-permission-remove-button:not(#hack) {
	background: transparent !important;
	box-shadow: none !important;
	border-color: transparent !important;
	border-radius: 5px !important;
}
.subviewbutton-back:not(#hack):not(:active):hover,
.close-icon:not(.tab-close-button):not(:active):hover,
#TabsToolbar .toolbarbutton-1:not(:active):not([open]):hover,
#protections-popup-show-report-button:not(:active):hover {
	box-shadow: var(--gnome-button-box-shadow) !important;
	border-color: var(--gnome-button-border-color) !important;
	border-bottom-color: var(--gnome-button-border-accent-color) !important;
}

/* Circle buttons */
#downloadsPanel-mainView .download-state .downloadButton,
.identity-popup-permission-remove-button:not(#hack) {
	border-radius: 100% !important;
}

/* Combined buttons */
#nav-bar .toolbaritem-combined-buttons toolbarbutton:not(:last-of-type):not(#hack),
#nav-bar #back-button:not(#hack),
.subviewbutton.panel-subview-footer:not(:only-of-type):not(:last-of-type),
.panel-footer button:not(:only-of-type):not(:last-of-type),
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not(:last-of-type):not(#appMenu-zoomEnlarge-button),
#context-navigation menuitem:not(:last-of-type),
.findbar-container toolbarbutton.findbar-find-previous,
.findbar-button:not(:last-of-type) {
	border-top-right-radius: 0 !important;
	border-bottom-right-radius: 0 !important;
	border-right-width: 0 !important;
	margin-right: 0 !important;
}

#nav-bar .toolbaritem-combined-buttons toolbarbutton:not(:first-of-type):not(#hack),
#nav-bar #forward-button:not(#hack),
.subviewbutton.panel-subview-footer:not(:only-of-type):not(:first-of-type),
.panel-footer button:not(:only-of-type):not(:first-of-type),
#appMenu-popup .toolbaritem-combined-buttons toolbarbutton:not(:first-of-type):not(#appMenu-fullscreen-button),
#context-navigation menuitem:not(:first-of-type),
.findbar-container toolbarbutton.findbar-find-previous,
.findbar-container toolbarbutton.findbar-find-next,
.findbar-button:not(:first-of-type) {
	border-top-left-radius: 0 !important;
	border-bottom-left-radius: 0 !important;
	margin-left: 0 !important;
}

#nav-bar .toolbaritem-combined-buttons {
	margin-left: 0 !important;
	margin-right: 0 !important;
}

/* Buttons with suggested action */
#appMenu-popup .panel-banner-item[notificationid="update-restart"],
button.popup-notification-primary-button,
#editBookmarkPanelDoneButton,
#tracking-action-block {
	color: white !important;
	background: var(--gnome-button-suggested-action-background) !important;
	border-color: var(--gnome-button-suggested-action-border-color) !important;
	border-bottom-color: var(--gnome-button-suggested-action-border-accent-color) !important;	
	box-shadow: var(--gnome-button-suggested-action-box-shadow) !important;
	text-shadow: 0 -1px rgba(0, 0, 0, 0.559216) !important;
}

#appMenu-popup .panel-banner-item[notificationid="update-restart"]:hover,
button.popup-notification-primary-button.popup-notification-button:hover,
#editBookmarkPanelDoneButton:hover,
#tracking-action-block:hover {
	background: var(--gnome-button-suggested-action-hover-background) !important;
}

#appMenu-popup .panel-banner-item[notificationid="update-restart"]:active,
button.popup-notification-primary-button.popup-notification-button:active,
#editBookmarkPanelDoneButton:active,
#tracking-action-block:active {
	background: var(--gnome-button-suggested-action-active-background) !important;
	border-color: var(--gnome-button-suggested-action-active-border-color) !important;
	box-shadow: var(--gnome-button-suggested-action-active-box-shadow) !important;
	text-shadow: none !important;
}

/* Buttons with destructive action */
#editBookmarkPanelRemoveButton,
.identity-popup-permission-remove-button,
#PanelUI-panic-view-button {
	color: white !important;
	background: var(--gnome-button-destructive-action-background) !important;
	border-color: var(--gnome-button-destructive-action-border-color) !important;
	border-bottom-color: var(--gnome-button-destructive-action-border-accent-color) !important;
	box-shadow: var(--gnome-button-destructive-action-box-shadow) !important;
	text-shadow: 0 -1px rgba(0, 0, 0, 0.558275) !important;
}

#editBookmarkPanelRemoveButton:hover,
.identity-popup-permission-remove-button:not(#hack):hover,
#PanelUI-panic-view-button:hover {
	background: var(--gnome-button-destructive-action-hover-background) !important;
}

#editBookmarkPanelRemoveButton:active,
.identity-popup-permission-remove-button:not(#hack):active,
#PanelUI-panic-view-button:active {
	background: var(--gnome-button-destructive-action-active-background) !important;
	border-color: var(--gnome-button-destructive-action-active-border-color) !important;
	box-shadow: var(--gnome-button-destructive-action-active-box-shadow) !important;
}

.identity-popup-permission-remove-button:not(#hack):hover { /* Is flat */
	border-color: var(--gnome-button-destructive-action-border-color) !important;
	border-bottom-color: var(--gnome-button-destructive-action-border-accent-color) !important;
	box-shadow: var(--gnome-button-destructive-action-box-shadow) !important;
}
.identity-popup-permission-remove-button:not(#hack):hover .button-icon {
	filter: invert(100%) brightness(200%);
}
	
/* User sync menu, bigger avatar */
#fxa-toolbar-menu-button .toolbarbutton-badge-stack {
	padding: 0 !important;
	margin: 0 !important;
}
#fxa-avatar-image {	
	height: 26px !important;
	margin: 0 !important;
	padding: 0 !important;
	width: 26px !important;
}
```
