### ISSUE TITLE
[Bug] [Help request] FGT with 5 undersized icons when `gnomeTheme.systemIcons` is `true` .

### ISSUE THREAD

**Issue by Fraxtux** [rafaelmardojai/firefox-gnome-theme#955]
### Describe the bug

![Image](https://github.com/user-attachments/assets/bfc56461-b0b5-4223-9985-4d7f0d5de75b)

When the Boolean option `gnomeTheme.systemIcons` is set to `true`, and when the Papirus Icon Theme is used, 5 icons, namely: forward, back, reload, close tab, and firefox menu are undersized.

### Steps to reproduce

- Use the pre-delivered version of Firefox on Fedora 42
- Install the FGT and the Papirus Icon Theme

- switch `gnomeTheme.systemIcons`  to `true` in `about:config`

### Expected behavior

The 5 icons mentioned should not be undersized...

### Operating System

Fedora 42 prerelease, Workstation Edition

### Firefox installation method

Distro package

### Firefox version

136.0.2 (64 bits)

### Theme version

branch gnome48

### Optional features enabled

- [x] gnomeTheme.hideSingleTab
- [ ] gnomeTheme.normalWidthTabs
- [ ] gnomeTheme.swapTabClose
- [x] gnomeTheme.bookmarksToolbarUnderTabs
- [ ] gnomeTheme.activeTabContrast
- [ ] gnomeTheme.closeOnlySelectedTabs
- [x] gnomeTheme.systemIcons
- [ ] gnomeTheme.noThemedIcons
- [ ] gnomeTheme.symbolicTabIcons
- [x] gnomeTheme.hideWebrtcIndicator
- [ ] gnomeTheme.hideUnifiedExtensions
- [x] gnomeTheme.dragWindowHeaderbarButtons
- [ ] gnomeTheme.tabsAsHeaderbar
- [ ] gnomeTheme.oledBlack
- [x] gnomeTheme.allTabsButtonOnOverflow
- [ ] gnomeTheme.allTabsButton
- [ ] gnomeTheme.tabAlignLeft
- [x] gnomeTheme.bookmarksOnFullscreen

### Additional information

@varlesh may have found the solution:

https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3994

**Comment by rafaelmardojai** [comment]
As I posted in the Papitus issue, removing `?size=dialog` will cause blurry icons on scaled monitors.

Here you have `system-icons.css` with `?size=dialog` removed in the go back icon (using adwaita icons in the system) and the screen scaled to 200%:

![Image](https://github.com/user-attachments/assets/d46e7df2-174d-4643-81b2-d29b1d2df886)

So is changing one bug for another. But the thing that makes me prefer stay as we are is the fact that so far `?size=dialog` has been working fine with other icon themes.

**Comment by Fraxtux** [comment]
I use a small screen, it doesn't affect me. Thanks!

**Comment by rafaelmardojai** [comment]
I have refactored icons to make `system-icons.css` cleaner.

For you use case you just need to change these lines:

https://github.com/rafaelmardojai/firefox-gnome-theme/blob/b58d48d1a465970af7d4161e913f153afd7917d2/theme/system-icons.css#L14-L45

With these:

```css
:root {
	--gnome-icon-application-x-addon-symbolic: url("moz-icon://stock/application-x-addon-symbolic") !important;
	--gnome-icon-applications-engineering-symbolic: url("moz-icon://stock/applications-engineering-symbolic") !important;
	--gnome-icon-edit-copy-symbolic: url("moz-icon://stock/edit-copy-symbolic") !important;
	--gnome-icon-edit-cut-symbolic: url("moz-icon://stock/edit-cut-symbolic") !important;
	--gnome-icon-edit-find-symbolic: url("moz-icon://stock/edit-find-symbolic") !important;
	--gnome-icon-edit-paste-symbolic: url("moz-icon://stock/edit-paste-symbolic") !important;
	--gnome-icon-folder-download-symbolic: url("moz-icon://stock/folder-download-symbolic") !important;
	--gnome-icon-go-next-symbolic: url("moz-icon://stock/go-next-symbolic") !important;
	--gnome-icon-go-previous-symbolic: url("moz-icon://stock/go-previous-symbolic") !important;
	--gnome-icon-mail-unread-symbolic: url("moz-icon://stock/mail-unread-symbolic") !important;
	--gnome-icon-open-menu-symbolic: url("moz-icon://stock/open-menu-symbolic") !important;
	--gnome-icon-pan-down-symbolic: url("moz-icon://stock/pan-down-symbolic") !important;
	--gnome-icon-pan-down-symbolic: url("moz-icon://stock/pan-down-symbolic") !important;
	--gnome-icon-preferences-system-symbolic: url("moz-icon://stock/preferences-system-symbolic") !important;
	--gnome-icon-preferences-system-time-symbolic: url("moz-icon://stock/preferences-system-time-symbolic") !important;
	--gnome-icon-printer-symbolic: url("moz-icon://stock/printer-symbolic") !important;
	--gnome-icon-process-stop-symbolic: url("moz-icon://stock/process-stop-symbolic") !important;
	--gnome-icon-starred-symbolic: url("moz-icon://stock/starred-symbolic") !important;
	--gnome-icon-tab-new-symbolic: url("moz-icon://stock/tab-new-symbolic") !important;
	--gnome-icon-user-home-symbolic: url("moz-icon://stock/user-home-symbolic") !important;
	--gnome-icon-view-fullscreen-symbolic: url("moz-icon://stock/view-fullscreen-symbolic") !important;
	--gnome-icon-view-refresh-symbolic: url("moz-icon://stock/view-refresh-symbolic") !important;
	--gnome-icon-view-restore-symbolic: url("moz-icon://stock/view-restore-symbolic") !important;
	--gnome-icon-window-close-symbolic: url("moz-icon://stock/window-close-symbolic") !important;
	--gnome-icon-window-maximize-symbolic: url("moz-icon://stock/window-maximize-symbolic") !important;
	--gnome-icon-window-minimize-symbolic: url("moz-icon://stock/window-minimize-symbolic") !important;
	--gnome-icon-window-new-symbolic: url("moz-icon://stock/window-new-symbolic") !important;
	--gnome-icon-window-restore-symbolic: url("moz-icon://stock/window-restore-symbolic") !important;
	--gnome-icon-zoom-in-symbolic: url("moz-icon://stock/zoom-in-symbolic") !important;
	--gnome-icon-zoom-out-symbolic: url("moz-icon://stock/zoom-out-symbolic") !important;
}
```

If you modify the theme, you probably want to check on creating a `customChrome.css`, see https://github.com/rafaelmardojai/firefox-gnome-theme/blob/b58d48d1a465970af7d4161e913f153afd7917d2/userChrome.css#L5-L9C10.
