### ISSUE TITLE
[Bug] Close buttons don't show up on inactive tabs

### ISSUE THREAD

**Issue by somepaulo** [rafaelmardojai/firefox-gnome-theme#967]
### Describe the bug

Close buttons don't show up on inactive tabs despite the `gnomeTheme.closeOnlySelectedTabs` option being disabled. I tried not having the option at all as well as having it explicitly set to `false`.

### Steps to reproduce

1. Open at least two tabs
2. Hover over the inactive tab
3. See no `close` button on that tab

### Expected behavior

A working `close` button should appear on hover over an inactive tab if the `gnomeTheme.closeOnlySelectedTabs` is not set.

### Operating System

Arch

### Firefox installation method

Distro package

### Firefox version

137.0

### Theme version

master branch

### Optional features enabled

- [ ] gnomeTheme.hideSingleTab
- [x] gnomeTheme.normalWidthTabs
- [ ] gnomeTheme.swapTabClose
- [ ] gnomeTheme.bookmarksToolbarUnderTabs
- [x] gnomeTheme.activeTabContrast
- [ ] gnomeTheme.closeOnlySelectedTabs
- [x] gnomeTheme.systemIcons
- [ ] gnomeTheme.noThemedIcons
- [ ] gnomeTheme.symbolicTabIcons
- [x] gnomeTheme.hideWebrtcIndicator
- [ ] gnomeTheme.hideUnifiedExtensions
- [ ] gnomeTheme.dragWindowHeaderbarButtons
- [ ] gnomeTheme.tabsAsHeaderbar
- [ ] gnomeTheme.oledBlack
- [ ] gnomeTheme.allTabsButtonOnOverflow
- [x] gnomeTheme.allTabsButton
- [ ] gnomeTheme.tabAlignLeft
- [ ] gnomeTheme.bookmarksOnFullscreen

### Additional information

It seems like the negative @media preference declaration doesn't work.
I was able to bring the buttons back with the following code in my customChrome.css:

```css
#tabbrowser-tabs[orient="horizontal"] tab:not([selected]):hover .tab-close-button {
  opacity: 1 !important;
  visibility: visible !important;

  @media (-moz-bool-pref: "gnomeTheme.closeOnlySelectedTabs") {
    opacity: 0 !important;
    visibility: hidden !important;
  }
}
```
